defaults:
- _self_
- dataset:
#   - geographic_preservation
  - admixture_preservationk
# - embedding:
  # - trustworthiness
  # - tangent_space
# - module:
#   - connected_components
subsample_fraction: null
