[paths]
config_dir = "configs"
output_dir = "outputs"
tools_dir = "tools"

# Note: Defaults are now defined in configs/meta.yaml to avoid redundancy
# This file focuses on ExperimentStash-specific settings

[reproducibility]
pin_commits = false  # Allow branch tracking for development
validate_submodules = true
check_uncommitted_changes = true

[logging]
log_level = "INFO"
log_file = "outputs/logs/experiment.log"

[ci]
test_submodule_imports = true
test_config_loading = true
validate_paths = true
