wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  project: "ManyLatents"
  name: ${name}
  log_model: false
  save_dir: "."
  offline: False 
  id: null
  # entity: "" 
  prefix: ""
  job_type: "train"
  group: ""
  tags: []