_target_: manylatents.algorithms.latent.diffusionmap.DiffusionMapModule
n_components: 2
random_state: ${seed}
t: 5
knn: 100
decay: 40
n_pca: null
n_landmark: null
n_jobs: -1
verbose: False
fit_fraction: 1.0
