# analysis_experiment.yaml - Example analysis experiment
tool: hello-world

defaults:
  - _self_

experiment:
  name: "analysis_experiment"
  seed: 42
  description: "Analysis experiment to understand model behavior"

analysis:
  type: "feature_analysis"
  method: "pca"
  n_components: 10
  visualize: true

data:
  batch_size: 64
  num_workers: 4

trainer:
  max_epochs: 50
  learning_rate: 0.01

hydra:
  run:
    dir: outputs/analysis/${now:%Y-%m-%d}/${now:%H-%M-%S}
