# hello_world.yaml - Hello World experiment using the demo tool
tool: hello-world

experiment:
  name: "hello_world_demo"
  description: "Demonstration of the hello-world tool"
  simulate_work: true
  seed: 42

# Example of how to configure tool-specific parameters
hello_world:
  message: "Hello from the experiment template!"
  verbose: true
