runs:
  # Example Experiments
  pca_swissroll:
    tool: manylatents
    config: figure1_method_comparison/pca_swissroll
    description: "PCA on Swiss roll data"
    tags: ["pca", "swissroll", "method_comparison"]
    estimated_runtime: "30m"

  umap_swissroll:
    tool: manylatents
    config: figure1_method_comparison/umap_swissroll
    description: "UMAP on Swiss roll data"
    tags: ["umap", "swissroll", "method_comparison"]
    estimated_runtime: "45m"

  tsne_swissroll:
    tool: manylatents
    config: figure1_method_comparison/tsne_swissroll
    description: "t-SNE on Swiss roll data"
    tags: ["tsne", "swissroll", "method_comparison"]
    estimated_runtime: "60m"
