_target_: manylatents.algorithms.lightning.reconstruction.Reconstruction
datamodule: ${data}
network:
  _target_: manylatents.algorithms.lightning.networks.autoencoder.Autoencoder
  input_dim: null # must be currently specified from experiment
  hidden_dims: [512, 256, 128]
  latent_dim: 50
  activation: relu
  batchnorm: true
  dropout: 0.1
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
loss:
  _target_: manylatents.algorithms.lightning.losses.mse.MSELoss