_target_: manylatents.algorithms.reconstruction.Reconstruction
datamodule: ${data}
network:
  _target_: manylatents.algorithms.networks.autoencoder.Autoencoder
  input_dim: null # must be currently specified from experiment
  hidden_dims: [512, 256, 128]
  latent_dim: 50
  activation: relu
  batchnorm: true
  dropout: 0.1
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
loss:
  _target_: manylatents.algorithms.losses.geometric.AllGeomLoss
  loss_pr:
    _target_: manylatents.algorithms.losses.geometric.PRLoss
    lambda_pr: 0
    eps: 1e-8
  loss_aniso:
    _target_: manylatents.algorithms.losses.geometric.AnisotropyLoss
    lambda_aniso: 0
    eps: 1e-8
  loss_tsa:
    _target_: manylatents.algorithms.losses.geometric.TSALoss
    lambda_tsa: 0.1
    k: 25
    p: 1
    eps: 1e-8
    raw_proj: true
    input_dim: null ## similar as above, must be specified from experiment
    proj_dim: 50 ## equals to latent_dim
    proj_bias: false
    offload_cpu: true
