name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: latest

    - name: Install dependencies
      run: |
        uv sync --extra dev

    - name: Run framework tests
      run: |
        uv run python tests/test_workflow.py

    - name: Run validation tests
      run: |
        uv run python tests/test_validation.py

    - name: Test all scripts
      run: |
        uv run python tests/test_add_tool.py
        uv run python tests/test_remove_tool.py

    - name: Validate setup
      run: |
        uv run python scripts/validate_setup.py

    - name: Check template integrity
      run: |
        uv run python tests/test_template_integrity.py

  create-release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🎉 ExperimentStash Template Release

          This release includes:
          - ✅ Framework scripts for tool management
          - ✅ Robust experiment execution with error handling
          - ✅ Signal handling for SLURM environments
          - ✅ Comprehensive documentation and troubleshooting
          - ✅ Validation and testing infrastructure
          - ✅ Clean template structure for collaboration

          ## 🚀 Quick Start

          ```bash
          # Clone the template
          git clone <your-repo-url>
          cd experimentstash

          # Add your first tool
          python3 scripts/add_tool.py <tool-name> <github-url>

          # Create an experiment
          # Edit configs/example_experiment.yaml

          # Run the experiment
          python3 scripts/run_experiment <tool> <config>
          ```

          ## 📚 Documentation

          See the [README.md](README.md) for comprehensive documentation.
        draft: false
        prerelease: false
